### ISSUE TITLE
Dead links in Readme

### ISSUE THREAD

**Issue by kequach** [CLARIAH/tool-discovery#17]
I stumbled across this repo during research for my thesis about open research software. I noticed that the [production link ](https://tools.clariah.nl/) and the [link to the files](https://tools.dev.clariah.nl/files/) are broken.

**Comment by proycon** [comment]
Thanks! The production link is indeed a bit premature as the production server isn't running yet (see https://github.com/CLARIAH/clariah-plus/issues/129) , for now we have the development server at https://tools.dev.clariah.nl only.

The malfunctioning (HTTP 500) `files/` link is certainly a bug! I'll look into it!
