### ISSUE TITLE
Improve validation of developmentStatus and applicationCategory vocabularies

### ISSUE THREAD

**Issue by ddeboer** [CLARIAH/tool-discovery#30]
Currently the SHACL uses `skos:inScheme`, which requires one to write something like:

```json
    "developmentStatus": [
        "https://www.repostatus.org/#active",
        {
            "@id":  "https://w3id.org/research-technology-readiness-level#Level9Proven",
            "http://www.w3.org/2004/02/skos/core#inScheme": {
                "@id":  "https://w3id.org/research-technology-readiness-level"
            }
        }
    ],
```

https://github.com/netwerk-digitaal-erfgoed/dataset-register/blob/56ab91b91a0d0a5ae27f2f21e5dd145f187e8a5b/codemeta.json#L34-L42

**Comment by proycon** [comment]
Is `https://w3id.org/research-technology-readiness-levels` part of your codemeta.json's context? I wonder if adding that already fixes this.

The harvester pipeline makes codemetapy load the entire context graph (including https://w3id.org/research-technology-readiness-levels for this case, which includes precisely that bit you needed to inject manually). The harvesting pipeline even injects things in the context that were not explicitly specified, so all this information is available at the point the SHACL validation runs and things validate. But if some context is missing in the codemeta.json and validated against the SHACL, it might fail.

People indeed should not duplicate stuff from the context into their own codemeta.json.

**Comment by proycon** [comment]
There were some inconsistencies in the URI (level vs levels) in the instructions and reality, I think I fixed this now.

**Comment by proycon** [comment]
I'm wondering if `skos:inScheme` is a bit too strict for the SHACL validation, we could perhaps validate by just checking whether the beginning of URI corresponds?

**Comment by ddeboer** [comment]
Even the simpler

```
        sh:qualifiedValueShape [
            sh:class trl:TechnologyReadinessLevel
        ] ;
```

doesn’t work, presumably because SHACL only validates the data graph itself, not any JSON-LD contexts that it depends on:


```
$ pyshacl -s software.ttl -f turtle -df json-ld codemeta.json --allow-infos --allow-warnings -d

Constraint Violation in ClassConstraintComponent (http://www.w3.org/ns/shacl#ClassConstraintComponent):
	Severity: sh:Violation
	Source Shape: [ sh:class trl:TechnologyReadinessLevel ]
	Focus Node: trl:Level9Proven
	Value Node: trl:Level9Proven
	Message: Value does not have class trl:TechnologyReadinessLevel
```

**Comment by proycon** [comment]
> check string prefix, which feels slightly less semantic.

Yeah, that would withhold me from that option too, although it's probably the simplest.

> include the TRL ontology separately with pyshacl -e trl.jsonld -ef json-ld (apparently fetching over HTTP doesn’t work well, so you have to download the file first)

Yes, but it's not limited to the TRL ontology, you'd have to include several other context graphs as well where the same issue plays. 

Of course the third and simple way out is to use codemeta-harvester (which in turn uses codemetapy) for validation, as that will invoke pyshacl in the right way, but I agree it should also be doable without that extra overhead.
